### ISSUE TITLE
How to use this framework?

### ISSUE THREAD

**Issue by NTDXYG** [zetang94/ASE2023_kNM-LM#1]
请教一下如何使用kNN-LM。

我的理解是第一步先微调出相应的模型。
第二步将训练集中的数据构造为FAISS index。
第三步就是在预测的时候进行概率加权融合。

我比较困惑的是第二步和第三步的具体使用方法，能否在readme中说明，如何一步地一步地使用？

**Comment by mf1832146** [comment]
Readme已经更新了，这个方法可以看作是对微调模型的一种替代，因此直接使用huggingface上下载的模型就可以。
